CREATE TABLE `recommond_table` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `name` text CHARACTER SET utf8mb3 COMMENT '名字',
    `tag` varchar(255) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT '标签',
    `introduce` varchar(255) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT '简介',
    `poster` varchar(255) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT '封面',
    `author` varchar(255) CHARACTER SET utf8mb3 DEFAULT NULL COMMENT '作者',
    `instruct_path` text CHARACTER SET utf8mb3 COMMENT '蓝牙指令',
    `status` int DEFAULT '0' COMMENT '状态',
    `file_path` varchar(255) DEFAULT NULL COMMENT '文件地址',
    `vr_video_url` varchar(255) DEFAULT NULL COMMENT 'vr视频地址',
    `type` varchar(255) DEFAULT NULL COMMENT '类型：普通模式  normal\n视频模式  video\n音频模式 audio\n音乐模式 music',
    `duration` bigint DEFAULT NULL COMMENT '时长(毫秒) duration',
    `image_height` int DEFAULT NULL COMMENT '图片宽度，px',
    `image_width` int DEFAULT NULL COMMENT '图片高度，px',
    `service_level_limits` int DEFAULT NULL COMMENT '限制等级（0 大陆用户可用,1国外限制级 ,2 限制级别上升 ',
    `deleted_flag` tinyint DEFAULT NULL COMMENT '1:未删除\r\n-1：删除',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '修改时间',
    `likes_count` bigint DEFAULT '0' COMMENT '喜欢数量',
    `collection_count` bigint DEFAULT '0' COMMENT '收藏数量',
    `fake_collection_count` bigint DEFAULT NULL COMMENT '假收藏数',
    `is_old_version` tinyint(1) DEFAULT '0' COMMENT '是否是旧版（0 旧版  1 新版）',
    `novel_text_url` varchar(255) DEFAULT NULL COMMENT '小说url',
    `show_order` int DEFAULT '890' COMMENT '排序',
    `first_frame_url` varchar(255) DEFAULT NULL COMMENT '第一帧url',
    `gender` tinyint DEFAULT NULL COMMENT '性别',
    `selected_level` int DEFAULT '0',
    `xgame_supported` bit(1) DEFAULT b'0' COMMENT 'xgame支持',
    `vr_mode` int DEFAULT '0',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2025043002 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;